### PR TITLE
Remove CNAME

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by zachlatta** [comment]
:+1:

**Comment by TheThirdOne** [comment]
@MaxWofford, Any progress on another domain?

**Comment by zachlatta** [comment]
Why not throw it up on someone's subdomain?

**Comment by TheThirdOne** [comment]
@zachlatta, if it isn't on its own domain, we might as well use gh-pages directly as that essentially puts it in eshsprogramming's subdomain. 

Max had discussed using a namecheap coupon or .tech domain to keep it up.

**Comment by zachlatta** [comment]
Mmm, we could do .tech, but we'd only get it for a year for free.

I'm down with anything.

**Comment by maxwofford** [comment]
Going to personally use https://maxwofford.com/enomemes for this.

**Pull request merged**
